//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTICIA()
        {
            this.PERIODISTA = new HashSet<PERIODISTA>();
        }
    
        public string CodigoNoticia { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public int Importancia { get; set; }
        public string CodigoSeccion { get; set; }
        public string Usuario { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual SECCION SECCION { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual HashSet<PERIODISTA> PERIODISTA { get; set; }
    }
}
